### ISSUE TITLE
[Bug]: fatal error: Segmentation fault

### ISSUE THREAD

**Issue by YourDire** [snapcrafters/gimp#298]
### What happened?

I tried to select the locally installed LDFComicSans medium font in GIMP, but it crashed. After looking at the terminal output, I realized I had accidentally added my ~/home/ directory to the font directory, which may have contributed to the crash. Also, my Raspberry Pi 5 running Ubuntu 24.10 oracular has very limited memory. I would have ignored this crash if it weren’t for a different bash script I tried running earlier, which crashed with the same error message. I would appreciate any explanation of what happened or what the "Segmentation fault" is, as I am fairly new to linux.

### What should have happened?

GIMP should have selected the font.

### Output of `snap info $snap_name`

```shell
name:      gimp
summary:   GNU Image Manipulation Program
publisher: Snapcrafters✪
store-url: https://snapcraft.io/gimp
contact:   https://github.com/snapcrafters/gimp/issues
license:   unset
description: |
  Whether you are a graphic designer, photographer, illustrator, or
  scientist, GIMP provides you with sophisticated tools to get your job done.
  You can further enhance your productivity with GIMP thanks to many
  customization options and 3rd party plugins.
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
  
  Upstream Project: https://www.gimp.org/
  snapcraft.yaml Build Definition:
  https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
commands:
  - gimp
snap-id:      KDHYbyuzZukmLhiogKiUksByRhXD2gYV
tracking:     latest/stable
refresh-date: 2024-08-07
channels:
  latest/stable:     2.10.38   2024-05-10 (437) 484MB -
  latest/candidate:  2.10.38   2024-05-10 (437) 484MB -
  latest/beta:       ↑                                
  latest/edge:       ↑                                
  preview/stable:    3.0.0-RC1 2024-11-07 (453) 368MB -
  preview/candidate: 3.0.0-RC1 2024-11-06 (453) 368MB -
  preview/beta:      ↑                                
  preview/edge:      3.0.0-RC1 2024-11-07 (455) 368MB -
installed:           2.10.38              (437) 484MB -
```

### Output of `snap connections $snap_name`

```shell
Interface                 Plug                  Slot                              Notes
browser-support           gimp:browser-support  :browser-support                  -
content[gnome-3-38-2004]  gimp:gnome-3-38-2004  gnome-3-38-2004:gnome-3-38-2004   -
content[gtk-2-engines]    gimp:gtk-2-engines    gtk2-common-themes:gtk-2-engines  -
content[gtk-3-themes]     gimp:gtk-3-themes     gtk-common-themes:gtk-3-themes    -
content[icon-themes]      gimp:icon-themes      gtk-common-themes:icon-themes     -
content[sound-themes]     gimp:sound-themes     gtk-common-themes:sound-themes    -
cups-control              gimp:cups-control     -                                 -
dbus                      -                     gimp:dbus-gimp                    -
desktop                   gimp:desktop          :desktop                          -
desktop-legacy            gimp:desktop-legacy   :desktop-legacy                   -
gsettings                 gimp:gsettings        :gsettings                        -
home                      gimp:home             :home                             -
network                   gimp:network          :network                          -
opengl                    gimp:opengl           :opengl                           -
removable-media           gimp:removable-media  -                                 -
unity7                    gimp:unity7           :unity7                           -
wayland                   gimp:wayland          :wayland                          -
x11                       gimp:x11              :x11                              -
```

### Output of `snap version`

```shell
snap    2.66.1
snapd   2.66.1
series  16
ubuntu  24.10
kernel  6.11.0-1004-raspi
```

### Relevant log output

~~~shell
<!-- Copy-paste this whole debug data to report to developers -->



GNU Image Manipulation Program version 2.10.38
git-describe: GIMP_2_10_38
Build: org.gimp.GIMP.snapcraft.stable rev 0 for linux
# C compiler #
	Using built-in specs.
	COLLECT_GCC=gcc
	COLLECT_LTO_WRAPPER=/build/snapcraft-gimp-8cde565ba7aa0551faa448bffba919f6/stage/usr/bin/../lib/gcc/aarch64-linux-gnu/9/lto-wrapper
	Target: aarch64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
	Thread model: posix
	gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 

# Libraries #
using babl version 0.1.92 (compiled against version 0.1.92)
using GEGL version 0.4.38 (compiled against version 0.4.38)
using GLib version 2.64.6 (compiled against version 2.64.6)
using GdkPixbuf version 2.40.1 (compiled against version 2.40.0)
using GTK+ version 2.24.32 (compiled against version 2.24.32)
using Pango version 1.48.0 (compiled against version 1.44.7)
using Fontconfig version 2.13.1 (compiled against version 2.13.1)
using Cairo version 1.17.4 (compiled against version 1.16.0)

```
> fatal error: Segmentation fault

Stack trace:
```
/snap/gimp/437/usr/lib/libgimpbase-2.0.so.0(gimp_stack_trace_print+0x2bc)[0xffffa988e414]
/snap/gimp/437/usr/bin/gimp(+0x6b250c)[0xaaaab0ad250c]
/snap/gimp/437/usr/bin/gimp(+0x6b25d4)[0xaaaab0ad25d4]
/snap/gimp/437/usr/bin/gimp(+0x6b2600)[0xaaaab0ad2600]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0xffffaa127860]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_str_hash+0x0)[0xffffa8cf74f0]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_hash_table_lookup+0x48)[0xffffa8cf5cc8]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0(+0x65dac)[0xffffa999edac]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0(+0x6604c)[0xffffa999f04c]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0(gdk_drag_begin+0x100)[0xffffa998e490]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0(+0x28b3cc)[0xffffa9c8b3cc]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0(+0x28bf40)[0xffffa9c8bf40]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0(+0x141da4)[0xffffa9b41da4]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0(g_closure_invoke+0x19c)[0xffffa9065444]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0(+0x28ff4)[0xffffa9079ff4]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0(g_signal_emit_valist+0x700)[0xffffa9085928]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0(g_signal_emit+0x80)[0xffffa9086580]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0(+0x268f6c)[0xffffa9c68f6c]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0(gtk_propagate_event+0xac)[0xffffa9b3fc7c]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgtk-x11-2.0.so.0(gtk_main_do_event+0x334)[0xffffa9b4011c]
/snap/gimp/437/usr/lib/aarch64-linux-gnu/libgdk-x11-2.0.so.0(+0x5ce64)[0xffffa9995e64]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x288)[0xffffa8d0adc8]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(+0x5804c)[0xffffa8d0b04c]
/snap/gimp/437/data-dir/gnome-platform/usr/lib/aarch64-linux-gnu/libglib-2.0.so.0(g_main_loop_run+0x80)[0xffffa8d0b388]
/snap/gimp/437/usr/bin/gimp(app_run+0x45c)[0xaaaab0ad2c34]
/snap/gimp/437/usr/bin/gimp(main+0x388)[0xaaaab0500168]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0xe8)[0xffffa9f60e10]
/snap/gimp/437/usr/bin/gimp(+0xe0308)[0xaaaab0500308]

```
~~~

### Teminal output of app

```shell
/home/[REDACTED]/snap/gimp/common/.cache/gio-modules/libgvfsdbus.so: cannot open shared object file: No such file or directory
Failed to load module: /home/[REDACTED]/snap/gimp/common/.cache/gio-modules/libgvfsdbus.so
gimp_font_factory_recursive_add_fontdir: adding font file '[REDACTED]' failed.
gimp_font_factory_recursive_add_fontdir: adding font file '[REDACTED]' failed.
gimp_font_factory_recursive_add_fontdir: adding font file '[REDACTED]' failed.
gimp_font_factory_recursive_add_fontdir: adding font file '[REDACTED]' failed.
gimp_font_factory_recursive_add_fontdir: adding font file '[REDACTED]' failed.
gimp_font_factory_recursive_add_fontdir: adding font file '[REDACTED]' failed.

...

GIMP-Message: Some fonts failed to load:
- [REDACTED]
- [REDACTED]
- [REDACTED]
- [REDACTED]
- [REDACTED]
- [REDACTED]
- [REDACTED]

...

/home/[REDACTED]/snap/gimp/common/.cache/gio-modules/libgvfsdbus.so: cannot open shared object file: No such file or directory
Failed to load module: /home/[REDACTED]/snap/gimp/common/.cache/gio-modules/libgvfsdbus.so
/snap/gimp/437/usr/bin/gimp: (null)-WARNING: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by jnsgruk** [comment]
Hi, can you please try out the preview track and see if you still have the issue?

```
sudo snap refresh gimp --channel preview/stable
```

Thanks!

**Comment by jnsgruk** [comment]
Hi there! We recently merged a big overhaul of the GIMP snap, keeping us up to date with the latest 3.0 feature release.

The snap has been rebased on core24, has migrated to a much improved GNOME extension & content snap, and is now using many more components from the Ubuntu archive. Given either the version stated in this issue, or the last time the issue was updated, it's highly likely that the issue is resolved or is no longer relevant to the supported version of GIMP.

As part of getting the snap and the repo back on track, and to help us prioritise ongoing issues, I'm working through all issues that refer to older versions or haven't been updated in a while.

I'm closing this issue for now, but please comment if the issue still persists, and I'll reopen and prioritise getting it fixed, or at least get you an update!

**Comment by YourDire** [comment]
Hello! I'm really sorry for not following up with my bug report - I totally forgot about it, as I no longer actively use the machine this crash occurred on, and the last... Few months? Were really busy for me. Regardless, I really want to thank you for your work, GIMP is a really important tool for me. Sorry if commenting here messes up something, I'm still not really familiar with how issues are tracked in big projects. To be clear, I agree that this bug report should be closed, and I'll come back and make a proper one (or comment on this one) if this issue ever comes up again. Thank you again!
