### ISSUE TITLE
[Bug]: Gimp not opening.

### ISSUE THREAD

**Issue by Kyuyrii** [snapcrafters/gimp#314]
### What happened?

Gimp won't open.

### What should have happened?

Gimp will open.

### Output of `snap info $snap_name`

```shell
name:      gimp
summary:   GNU Image Manipulation Program
publisher: Snapcrafters✪
store-url: https://snapcraft.io/gimp
contact:   https://github.com/snapcrafters/gimp/issues
license:   unset
description: |
  Whether you are a graphic designer, photographer, illustrator, or
  scientist, GIMP provides you with sophisticated tools to get your job done.
  You can further enhance your productivity with GIMP thanks to many
  customization options and 3rd party plugins.
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
  
  Upstream Project: https://www.gimp.org/
  snapcraft.yaml Build Definition:
  https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
commands:
  - gimp
snap-id:      KDHYbyuzZukmLhiogKiUksByRhXD2gYV
tracking:     latest/stable
refresh-date: today at 10:04 -03
channels:
  latest/stable:           2.10.38   2024-05-10 (436) 540MB -
  latest/candidate:        2.10.38   2024-05-10 (436) 540MB -
  latest/beta:             ↑                                
  latest/edge:             ↑                                
  preview/stable:          3.0.0-RC1 2024-12-04 (457) 388MB -
  preview/candidate:       3.0.0-RC1 2024-12-04 (457) 388MB -
  preview/beta:            ↑                                
  preview/edge:            3.0.0-RC1 2024-12-04 (459) 388MB -
  2.99-openvino/stable:    –                                
  2.99-openvino/candidate: 2.99.16   2024-12-20 (465) 387MB -
  2.99-openvino/beta:      ↑                                
  2.99-openvino/edge:      ↑                                
installed:                 2.10.38              (436) 540MB -
```

### Output of `snap connections $snap_name`

```shell
Interface        Plug                  Slot              Notes
browser-support  gimp:browser-support  :browser-support  -
content          gimp:gnome-3-38-2004  -                 -
content          gimp:gtk-2-engines    -                 -
content          gimp:gtk-3-themes     -                 -
content          gimp:icon-themes      -                 -
content          gimp:sound-themes     -                 -
cups-control     gimp:cups-control     -                 -
dbus             -                     gimp:dbus-gimp    -
desktop          gimp:desktop          :desktop          -
desktop-legacy   gimp:desktop-legacy   :desktop-legacy   -
gsettings        gimp:gsettings        :gsettings        -
home             gimp:home             :home             -
network          gimp:network          :network          -
opengl           gimp:opengl           :opengl           -
removable-media  gimp:removable-media  -                 -
unity7           gimp:unity7           :unity7           -
wayland          gimp:wayland          :wayland          -
x11              gimp:x11              :x11              -
```

### Output of `snap version`

```shell
snap    2.67+git105.gbc60ea4
snapd   2.67+git105.gbc60ea4
series  16
ubuntu  24.10
kernel  6.11.0-13-generic
```

### Teminal output of app

```shell
/snap/gimp/436/snap/command-chain/desktop-launch: line 20: /snap/gimp/436/data-dir/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: No such file or directory
/snap/gimp/436/usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0: error while loading shared libraries: libpango-1.0.so.0: cannot open shared object file: No such file or directory
ERROR: /snap/gimp/436/data-dir/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 exited abnormally with status 127
ERROR: /snap/gimp/436/usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 exited abnormally with status 127
/snap/gimp/436/usr/bin/gimp: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by Kyuyrii** [comment]
Trying to open it for the second time through the terminal, this is what appears:

/snap/gimp/436/usr/bin/gimp: error while loading shared libraries: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by dennn13** [comment]
Try this https://github.com/snapcrafters/gimp/issues/313#issuecomment-2564293737 worked for me.

**Comment by Kyuyrii** [comment]
The command   ```sudo snap connect gimp:gnome-3-38-2004 gnome-3-38-2004:gnome-3-38-2004``` solved the problem, thanks for the help.

Apparently Gimp lost automatic connection with this "gnome-3-38-2004", this month I installed Gimp several times and it was opening normally.

It was only this week that it started not being able to open.

I hope this is resolved soon.

**Comment by jdaviescoates** [comment]
> The command `sudo snap connect gimp:gnome-3-38-2004 gnome-3-38-2004:gnome-3-38-2004` solved the problem, thanks for the help.

I can now open Gimp after running that too, but I still get these errors and warnings:

/snap/gimp/436/usr/bin/gimp: Gimp-Widgets-WARNING: parse_iso_codes: error parsing '/usr/share/xml/iso-codes/iso_639.xml': No such file or directory


(gimp:74376): Gtk-WARNING **: 16:51:57.543: Unable to locate theme engine in module_path: "pixmap",

I thought part of the whole point of Snaps was to ensure all dependencies are included :thinking:  

It's rather frustrating that just installing and opening a pretty standard app requires such debugging :sob:

**Comment by jnsgruk** [comment]
Hi! Sorry about this - based on a message I received from the store team today, this should now be resolved with refreshes/installs.  Sorry for the inconvenience.
