### ISSUE TITLE
[2.10.2] Open Location fails: volume doesn't implement mount

### ISSUE THREAD

**Issue by marcelpaulo** [snapcrafters/gimp#32]
Opening an image from a HTTPS location fails with error:

`volume doesn't implement mount`

Here's a screenshot when I tried to open *https://www.howtogeek.com/wp-content/uploads/2016/04/img_571c03f856528.png*:
![image](https://user-images.githubusercontent.com/10074769/40982739-601c9a82-68b4-11e8-9fa3-f55da3096ed0.png)

The error is the same for HTTP locations. The flatpak version doesn't have this issue, so it's not a GIMP generic issue.

I'm running GIMP *2.10.2* on Xubuntu 18.04.

**Comment by therealfarfetchd** [comment]
I get this same error, also for http. gimp 2.10.2-3 on Artix Linux

**Comment by diddledan** [comment]
This is likely due to the fact that I didn't give gimp network access permission. I did not think it likely that gimp would ever need to be able to access the network in it's job of editing images. I can add the plug to give the snap permission to access the network, though I'm not sure it is a good idea.

**Comment by marcelpaulo** [comment]
> I did not think it likely that gimp would ever need to be able to access the network in it's job of editing images

I use it frequently, I'd imagine it's common, for getting and editing images from the Web, instead of saving the image locally and then opening it on GIMP. I configured `Clipman` to open GIMP whenever an image URL is copied to the clipboard, so, editing an image on the Web boils down to right-clicking on the image and then (on Chrome) on `Copy image address`. It's a lean workflow, as long as GIMP has network access.

I much preferred snap GIMP than flatpak GIMP: it loads much more quickly and snap updates work out of the box (I had to set up a systemd timer to fire flatpak updates daily). But I installed flatpak GIMP because it has network access, so it fits in my workflow.

**Comment by marcelpaulo** [comment]
Actually, I'm just waiting for snap GIMP to get network access, when I'll ditch flatpak GIMP once and for all and install snap GIMP.

**Comment by azatoth** [comment]
Similar issue is still present in 2.10.24 and with all permissions available to be enabled.
![Screenshot from 2021-08-18 21-47-53](https://user-images.githubusercontent.com/146477/129963182-85b9988b-dff8-421f-99af-c13dace6d28b.png)

The UI doesn't indicate any error code at all though but it just doesn't show any progress
![Screenshot from 2021-08-18 21-53-30](https://user-images.githubusercontent.com/146477/129963302-30792161-1010-4b6d-b2ac-0874a01e3aca.png)

The console is printing out following:

> `file_open_image: mounting remote volume failed, trying to downloadthe file: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.708" (uid=1000 pid=248857 comm="/snap/gimp/372/usr/bin/gimp " label="snap.gimp.gimp (enforce)") interface="org.gtk.vfs.MountTracker" member="MountLocation" error name="(unset)" requested_reply="0" destination=":1.3" (uid=1000 pid=1563 comm="/usr/libexec/gvfsd " label="unconfined")`

**Comment by jnsgruk** [comment]
Hi there! We recently merged a big overhaul of the GIMP snap, keeping us up to date with the latest 3.0 feature release.

The snap has been rebased on core24, has migrated to a much improved GNOME extension & content snap, and is now using many more components from the Ubuntu archive. Given either the version stated in this issue, or the last time the issue was updated, it's highly likely that the issue is resolved or is no longer relevant to the supported version of GIMP.

As part of getting the snap and the repo back on track, and to help us prioritise ongoing issues, I'm working through all issues that refer to older versions or haven't been updated in a while.

I'm closing this issue for now, but please comment if the issue still persists, and I'll reopen and prioritise getting it fixed, or at least get you an update!

**Comment by grant-h** [comment]
Issue still present on 3.0.2 Ubuntu 20.04 Wayland. 

```
Apr 11 13:30:54 xxx dbus-daemon[nnn]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/gtk/MountOperationHandler" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.25" pid=1342877 label="snap.gimp.gimp" peer_pid=nnnn peer_label="unconfined"
Apr 11 13:30:54 xxx gimp_gimp.desktop[nnn]: file_open_image: mounting remote volume failed, trying to download the file: volume doesn’t implement mount
```

Occurs when trying to download a file or perform a drag and drop operation from firefox.

**Comment by jnsgruk** [comment]
Related: https://github.com/ubuntu/snapcraft-desktop-helpers/issues/135
